-- Create Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    -- In real app, hash this
    role VARCHAR2(20) DEFAULT 'STAFF' CHECK (role IN ('ADMIN', 'STAFF'))
);
-- Create Products Table
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0
);
-- Create Orders Table
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100),
    total_amount NUMBER(10, 2),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id NUMBER,
    payment_method VARCHAR2(20),
    card_number VARCHAR2(20),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
-- Create Order Items Table
CREATE TABLE order_items (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL,
    price_at_purchase NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);
-- Insert Default Admin User
INSERT INTO users (username, password, role)
VALUES ('admin', 'admin123', 'ADMIN');
-- Insert Service Boy User
INSERT INTO users (username, password, role)
VALUES ('service', 'service123', 'STAFF');
-- Insert Sample Products
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Espresso', 'Coffee', 3.50, 100);
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Cappuccino', 'Coffee', 4.50, 100);
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Latte', 'Coffee', 4.75, 100);
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Mocha', 'Coffee', 5.00, 100);
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Croissant', 'Food', 3.00, 50);
INSERT INTO products (name, category, price, stock_quantity)
VALUES ('Muffin', 'Food', 2.50, 50);
COMMIT;